apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-ci-go
  namespace: gitlab-system
spec:
  selector:
    matchLabels:
      app: gitlab-ci-go
  template:
    metadata:
      labels:
        app: gitlab-ci-go
    spec:
      containers:
      - name: gitlab-ci-go
        image: CI_REGISTRY_IMAGE:CI_COMMIT_SHORT_SHA
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ci-go
  namespace: gitlab-system
spec:
  selector:
    app: gitlab-ci-go
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab-ci-go
  namespace: gitlab-system
  labels:
    name: gitlab-ci-go
spec:
  ingressClassName: nginx
  rules:
  - host: test.sxxpqp.top
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gitlab-ci-go
            port: 
              number: 8080
